In [1]:
%pylab inline
import numpy as np
import pandas as pd
data = []
datapath = '/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/CN_Futures_2014.01.22.csv'
data = pd.read_csv(datapath)
data_CNF14 = data[data.Series == 'CNF14']
data = data_CNF14

Populating the interactive namespace from numpy and matplotlib

In [73]:
import time
start = time.time()

order_book_bid = []
order_book_ask = []
timestamp = data.TimeStamp[0]
temp_ask = 0
temp_bid = 0
bid = []
ask = []
timestamp_ = []
x = data.TimeStamp.unique()
#a = range(0,len(data.TimeStamp.unique()),1000)
time_contain = []
time_book_sorting = []
timestamp_.append(x[0])
y = data[data['TimeStamp'].str.contains(x[0])]
bid.append(y[(y.BidOrAsk == 'B')][["Price","OrderNumber","QuantityDifference"]]) # bid
ask.append(y[(y.BidOrAsk == 'A')][["Price","OrderNumber","QuantityDifference"]]) # ask
a = bid[0].sort(['Price'],ascending = [False])
b = ask[0].sort(['Price'],ascending = [True])    
order_book_bid.append(a[a.QuantityDifference != 0])
order_book_ask.append(b[b.QuantityDifference != 0])

for i in range(len(y),3200,1):    
    if data.BidOrAsk[i] == 'A' :
        #print i 
        #print temp_ask
        #print x[temp_ask]
        #print data[i:i+1][['Price',"OrderNumber","QuantityDifference"]]
        #print data.TimeStamp[i] == x[temp_ask]
        #print data[i:i+1][['QuantityDifference']] > 0,int(data[['QuantityDifference']][i:i+1].values)  
        if int(data[['QuantityDifference']][i:i+1].values) > 0 :
            if data.TimeStamp[i] == x[temp_ask]:            
                #print len(order_book_ask[temp_ask][(order_book_ask[temp_ask].Price == int(data[i:i+1][['Price']].values))]) >= 1                 
                if len(order_book_ask[temp_ask][(order_book_ask[temp_ask].Price == int(data[i:i+1][['Price']].values))]) >= 1:
                
                    legth_same_price = len(order_book_ask[temp_ask][(order_book_ask[temp_ask].Price == int(data[i:i+1][['Price']].values))])
                    #print order_book_ask[temp_ask][(order_book_ask[temp_ask].Price == int(data[i:i+1][['Price']].values))].index[0]
                    #print legth_same_price
                    #print order_book_ask[temp_ask]
                    position_ = order_book_ask[temp_ask][(order_book_ask[temp_ask].Price == int(data[i:i+1][['Price']].values))].index[0] + legth_same_price + 1
                    #print position_
                    Order_Position = data[i:i+1][['OrderBookPosition']].iloc[0].values
                    #print Order_Position
                    ##print position_ == Order_Position
                    order_book_ask[temp_ask] = pd.concat([order_book_ask[temp_ask],data[i:i+1][['Price',"OrderNumber",'QuantityDifference']]])
                    order_book_ask[temp_ask] = order_book_ask[temp_ask].sort(['Price'],ascending = [True])
                else:
                    position_ = order_book_ask[temp_ask][(order_book_ask[temp_ask].Price == int(data[i:i+1][['Price']].values))].index + 1
                    #print position_
                    order_book_ask[temp_ask] = pd.concat([order_book_ask[temp_ask],data[i:i+1][['Price',"OrderNumber",'QuantityDifference']]])
                    order_book_ask[temp_ask] = order_book_ask[temp_ask].sort(['Price'],ascending = [True])
                    order_book_ask[temp_ask] = pd.DataFrame(order_book_ask[temp_ask].values,columns = ['Price',"OrderNumber",'QuantityDifference'])                
                    #print order_book_ask[temp_ask]
                    position_ = order_book_ask[temp_ask][(order_book_ask[temp_ask].Price == int(data[i:i+1][['Price']].values))].index + 1
                    Order_Position = data[i:i+1][['OrderBookPosition']].iloc[0].values
                    ##print position_ == Order_Position
                #print '\t' 
            
            elif data.TimeStamp[i] != x[temp_ask]:
                #print len(order_book_ask[temp_ask][(order_book_ask[temp_ask].Price == int(data[i:i+1][['Price']].values))]) >= 1
                
                if len(order_book_ask[temp_ask][(order_book_ask[temp_ask].Price == int(data[i:i+1][['Price']].values))]) >= 1:
                    legth_same_price = len(order_book_ask[temp_ask][(order_book_ask[temp_ask].Price == int(data[i:i+1][['Price']].values))])                
                    order_book_ask.append(0)
                    temp_ask = temp_ask + 1
                    order_book_ask[temp_ask] = pd.concat([order_book_ask[temp_ask - 1],data[i:i+1][['Price',"OrderNumber",'QuantityDifference']]])
                    order_book_ask[temp_ask] = order_book_ask[temp_ask].sort(['Price'],ascending = [True])
                    order_book_ask[temp_ask] = pd.DataFrame(order_book_ask[temp_ask].values,columns = ['Price',"OrderNumber",'QuantityDifference'])                
                    position_ = order_book_ask[temp_ask][(order_book_ask[temp_ask].Price == int(data[i:i+1][['Price']].values))].index[0] + legth_same_price + 1
                    #print position_
                    Order_Position = data[i:i+1][['OrderBookPosition']].iloc[0].values
                    #print legth_same_price
                    #print order_book_ask[temp_ask]
                    #print int(data[i:i+1][['Price']].values)
                    ##print position_ == Order_Position
                else:
                    order_book_ask.append(0)
                    temp_ask = temp_ask + 1
                    order_book_ask[temp_ask] = pd.concat([order_book_ask[temp_ask - 1],data[i:i+1][['Price',"OrderNumber",'QuantityDifference']]])
                    #print order_book_ask[temp_ask]
                    order_book_ask[temp_ask] = order_book_ask[temp_ask].sort(['Price'],ascending = [True])
                    order_book_ask[temp_ask] = pd.DataFrame(order_book_ask[temp_ask].values,columns = ['Price',"OrderNumber",'QuantityDifference'])
                    #print order_book_ask[temp_ask]
                    #print int(data[i:i+1][['Price']].values)
                    position_ = order_book_ask[temp_ask][(order_book_ask[temp_ask].Price == int(data[i:i+1][['Price']].values))].index + 1
                    ##print position_ == data[i:i+1][['OrderBookPosition']].iloc[0]                                       

                order_book_ask[temp_ask] = order_book_ask[temp_ask].sort(['Price'],ascending = [True])
                #print '\t'                                          
                 
        elif int(data[['QuantityDifference']][i:i+1].values) < 0:
            Price_ =  int(data[['Price']][i:i+1].values)
            Order_Number_ = data[['OrderNumber']][i:i+1].iloc[0] 
            position_ = int(data[['OrderBookPosition']][i:i+1].values)
            index_ = order_book_ask[temp_ask][(order_book_ask[temp_ask].Price == Price_)].index + 1
            #if len(index_[index_ == position_]) == 1:
            #    print [True]
                
            #print index_
            #print position_
            #print Order_Number_ 
            #print order_book_ask[temp_ask]
            
            drop_values_ = pd.concat([order_book_ask[temp_ask],data[i:i+1][['Price',"OrderNumber",'QuantityDifference']]])
            
            order_book_ask[temp_ask] = drop_values_[['Price',"OrderNumber",'QuantityDifference']].groupby(by = ['Price','OrderNumber'],as_index = False)['QuantityDifference'].sum()
            #print order_book_ask[temp_ask]
            order_book_ask[temp_ask] = order_book_ask[temp_ask][order_book_ask[temp_ask].QuantityDifference != 0]
            order_book_ask[temp_ask] = pd.DataFrame(order_book_ask[temp_ask].values,columns = ['Price',"OrderNumber",'QuantityDifference'])
            #print order_book_ask[temp_ask]
            #print '\t' 

    elif data.BidOrAsk[i] == 'B' :
        #print i 
        #print temp_ask
        #print x[temp_ask]
        #print data[i:i+1][['Price',"OrderNumber","QuantityDifference"]]
        #print data.TimeStamp[i] == x[temp_ask]
        #print data[i:i+1][['QuantityDifference']] > 0,int(data[['QuantityDifference']][i:i+1].values)
        
        if int(data[['QuantityDifference']][i:i+1].values) > 0 :
            if data.TimeStamp[i] == x[temp_bid]:            
                #print len(order_book_bid[temp_bid][(order_book_bid[temp_bid].Price == int(data[i:i+1][['Price']].values))]) >= 1                 
                if len(order_book_bid[temp_bid][(order_book_bid[temp_bid].Price == int(data[i:i+1][['Price']].values))]) >= 1:
                
                    legth_same_price = len(order_book_bid[temp_bid][(order_book_ask[temp_bid].Price == int(data[i:i+1][['Price']].values))])
                    #print order_book_bid[temp_bid][(order_book_ask[temp_bid].Price == int(data[i:i+1][['Price']].values))].index[0]
                    #print legth_same_price
                    #print order_book_bid[temp_bid]
                    position_ = order_book_bid[temp_bid][(order_book_bid[temp_bid].Price == int(data[i:i+1][['Price']].values))].index[0] + legth_same_price + 1
                    #print position_
                    Order_Position = data[i:i+1][['OrderBookPosition']].iloc[0].values
                    #print Order_Position
                    ##print position_ == Order_Position
                    order_book_bid[temp_bid] = pd.concat([order_book_bid[temp_bid],data[i:i+1][['Price',"OrderNumber",'QuantityDifference']]])
                    order_book_bid[temp_bid] = order_book_bid[temp_bid].sort(['Price'],ascending = [False])
                else:
                    position_ = order_book_bid[temp_bid][(order_book_bid[temp_bid].Price == int(data[i:i+1][['Price']].values))].index + 1
                    #print position_
                    order_book_bid[temp_bid] = pd.concat([order_book_bid[temp_bid],data[i:i+1][['Price',"OrderNumber",'QuantityDifference']]])
                    order_book_bid[temp_bid] = order_book_bid[temp_bid].sort(['Price'],ascending = [False])
                    order_book_bid[temp_bid] = pd.DataFrame(order_book_bid[temp_bid].values,columns = ['Price',"OrderNumber",'QuantityDifference'])                
                    #print order_book_bid[temp_bid]
                    position_ = order_book_bid[temp_bid][(order_book_bid[temp_bid].Price == int(data[i:i+1][['Price']].values))].index + 1
                    Order_Position = data[i:i+1][['OrderBookPosition']].iloc[0].values
                    ##print position_ == Order_Position
                #print '\t' 
            
            elif data.TimeStamp[i] != x[temp_bid]:
                #print len(order_book_bid[temp_bid][(order_book_bid[temp_bid].Price == int(data[i:i+1][['Price']].values))]) >= 1
                
                if len(order_book_bid[temp_bid][(order_book_bid[temp_bid].Price == int(data[i:i+1][['Price']].values))]) >= 1:
                    legth_same_price = len(order_book_bid[temp_bid][(order_book_bid[temp_bid].Price == int(data[i:i+1][['Price']].values))])                
                    order_book_bid.append(0)
                    temp_bid = temp_bid + 1
                    order_book_bid[temp_bid] = pd.concat([order_book_bid[temp_bid - 1],data[i:i+1][['Price',"OrderNumber",'QuantityDifference']]])
                    order_book_bid[temp_bid] = order_book_bid[temp_bid].sort(['Price'],ascending = [False])
                    order_book_bid[temp_bid] = pd.DataFrame(order_book_bid[temp_bid].values,columns = ['Price',"OrderNumber",'QuantityDifference'])                
                    position_ = order_book_bid[temp_bid][(order_book_bid[temp_bid].Price == int(data[i:i+1][['Price']].values))].index[0] + legth_same_price + 1
                    #print position_
                    Order_Position = data[i:i+1][['OrderBookPosition']].iloc[0].values
                    #print legth_same_price
                    #print order_book_ask[temp_ask]
                    #print int(data[i:i+1][['Price']].values)
                    ##print position_ == Order_Position
                else:
                    order_book_bid.append(0)
                    temp_bid = temp_bid + 1
                    order_book_bid[temp_bid] = pd.concat([order_book_bid[temp_bid - 1],data[i:i+1][['Price',"OrderNumber",'QuantityDifference']]])
                    #print order_book_bid[temp_bid]
                    order_book_bid[temp_bid] = order_book_bid[temp_bid].sort(['Price'],ascending = [False])
                    order_book_bid[temp_bid] = pd.DataFrame(order_book_bid[temp_bid].values,columns = ['Price',"OrderNumber",'QuantityDifference'])
                    #print order_book_bid[temp_bid]
                    #print int(data[i:i+1][['Price']].values)
                    position_ = order_book_bid[temp_bid][(order_book_bid[temp_bid].Price == int(data[i:i+1][['Price']].values))].index + 1
                    ##print position_ == data[i:i+1][['OrderBookPosition']].iloc[0]                                       

                order_book_bid[temp_bid] = order_book_bid[temp_bid].sort(['Price'],ascending = [False])
                #print '\t'                                          
                 
        elif int(data[['QuantityDifference']][i:i+1].values) < 0:
            Price_ =  int(data[['Price']][i:i+1].values)
            Order_Number_ = data[['OrderNumber']][i:i+1].iloc[0] 
            position_ = int(data[['OrderBookPosition']][i:i+1].values)
            index_ = order_book_bid[temp_bid][(order_book_bid[temp_bid].Price == Price_)].index + 1
            #if len(index_[index_ == position_]) == 1:
            #    print [True]
                
            #print index_
            #print position_
            #print Order_Number_ 
            #print order_book_ask[temp_ask]
            
            drop_values_ = pd.concat([order_book_bid[temp_bid],data[i:i+1][['Price',"OrderNumber",'QuantityDifference']]])
            
            order_book_bid[temp_bid] = drop_values_[['Price',"OrderNumber",'QuantityDifference']].groupby(by = ['Price','OrderNumber'],as_index = False)['QuantityDifference'].sum()
            #print order_book_bid[temp_bid]
            order_book_bid[temp_bid] = order_book_bid[temp_bid][order_book_bid[temp_bid].QuantityDifference != 0]
            order_book_bid[temp_bid] = pd.DataFrame(order_book_bid[temp_bid].values,columns = ['Price',"OrderNumber",'QuantityDifference'])
            #print order_book_bid[temp_bid]
            #print '\t'             
end = time.time()            
print "Total time = %f"%(end - start)

/home/bigdatas16/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:20: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
/home/bigdatas16/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:21: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
/home/bigdatas16/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:83: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
/home/bigdatas16/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:90: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
/home/bigdatas16/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:173: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
/home/bigdatas16/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:180: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
/home/bigdatas16/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:143: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
/home/bigdatas16/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:53: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
/home/bigdatas16/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:48: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
/home/bigdatas16/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:159: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
/home/bigdatas16/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:69: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

Total time = 77.222971

In [78]:
import time
start = time.time()
order_book_bid_merge = []
order_book_ask_merge = []
for i in range(0,len(order_book_bid)):
    a = order_book_bid[i][['Price','QuantityDifference']].groupby(by = ['Price'],as_index = False).sum().sort(['Price'],ascending = [False])
    order_book_bid_merge.append(pd.DataFrame(a.values))
for i in range(0,len(order_book_ask)):
    a = order_book_ask[i][['Price','QuantityDifference']].groupby(by = ['Price'],as_index = False).sum()#.sort(['Price'],ascending = [True])
    order_book_ask_merge.append(pd.DataFrame(a.values))
end = time.time()            
print "Total time = %f"%(end - start)

/home/bigdatas16/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:6: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

Total time = 19.222936

In [76]:
data.TimeStamp.unique()[2000]

'2014-01-22D09:16:30.273821100'

In [77]:
data[(data.TimeStamp == '2014-01-22D09:16:30.273821100')]

,Series,SequenceNumber,TimeStamp,OrderNumber,OrderBookPosition,Price,QuantityDifference,Trade,BidOrAsk,BestPrice,BestQuantity
3167,CNF14,3168,2014-01-22D09:16:30.273821100,6EDD013159F73A77,1,668500,-8,,B,668500,10

In [42]:
def fun_(data):
    print data[['Price']]

In [70]:
len(order_book_ask)

5022

In [72]:
len(order_book_bid)

4834

In [69]:
len(data[0:20000][(data[0:20000].BidOrAsk == 'A')].TimeStamp.unique())

6574

In [71]:
len(data[0:20000][(data[0:20000].BidOrAsk == 'B')].TimeStamp.unique())

6829

In [6]:
order_book_bid[10][['Price','QuantityDifference']]

     Price QuantityDifference
0   667000                 20
2   666500                 10
1   666500                 10
3   666000                 20
4   666000                 20
5   665500                 20
6   665000                 20
7   665000                 20
8   664500                 20
10  664000                 20
9   664000                  1
11  662500                  1
12  662000                  1
13  660500                  1
14  660000                 78
15  656500                  1
16  656500                  1
17  640000                100

In [29]:
order_book_bid_merge[240]

         0    1
0   668000   23
1   667500  125
2   667000  140
3   666500   56
4   666000  297
5   665500   36
6   665000   81
7   664500  136
8   664000  330
9   663500   96
10  663000  163
11  662500  132
12  662000  132
13  661500  193
14  661000    2
15  660500  203
16  660000  203
17  659500  100
18  659000  104
19  658500  100
20  658000  100
21  657500  100
22  657000  300
23  656500    4
24  655000  246
25  654500  100
26  654000  101
27  653500  500
28  653000  101
29  651500   10
30  650500   41
31  650000  541
32  649000   73
33  648500  181
34  648000   89
35  647000   80
36  646500  134
37  646000   78
38  643000    1
39  641500   20
40  640000    1
41  635000   10
42  633000    1
43  623000    1

In [53]:
a = order_book_ask[1][['Price','QuantityDifference']].groupby(by = ['Price'],as_index = False)['QuantityDifference'].sum().sort(['Price'],ascending = [True])
pd.DataFrame(a.values)#.reindex(index = arange(0,len(a),1))

/home/bigdatas16/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

           0      1
0   671500.0   20.0
1   672000.0   20.0
2   672500.0   30.0
3   673000.0   20.0
4   673500.0   20.0
5   674000.0   20.0
6   680000.0  100.0
7   681000.0   10.0
8   682500.0    1.0
9   689500.0    2.0
10  693000.0    1.0
11  710000.0    2.0
12  719500.0    1.0

In [16]:
len(order_book_bid)
a = order_book_bid[2000]

      Price       OrderNumber QuantityDifference
0    623000  642B4F585F7041F0                  1
1    633000  64234F58B6B09930                  1
2    635000  62606F00F550D770                 10
3    640000  46F7CF1878C65AE6                  1
4    641500  614508F57FEB642B                 20
5    643000  E42B4F50BDE6A066                  1
6    646000  4CB0EF1836421882                 78
7    646500  4460EF4007B2EA13                 66
8    646500  E663CF50B71D993D                 68
9    647000  66E3CF501070F291                 80
10   648000  607CEB4898377A57                 89
11   648500  4C30EF186F6C51AC                 95
12   648500  6663CF50F537D757                 86
13   649000  E6EB4F58EA9ACCBA                 73
14   650000  6AA06F40B2459465                  1
15   650000  C4E86F4875B15811                 41
16   650500  E66B4F58BA959CB5                 41
17   651500  49CC20F1023AE55B                 10
18   652000  658908F53EE92329                500
19   653000  E0F46B481E1B003B                100
20   653000  E4A34F5021A50425                  1
21   653500  44B86F1041192359                100
22   654000  4CE06748E658C8B8                100
23   654000  E99CA4F120F60416                  1
24   654500  E07C6B404FD631F6                100
25   655000  4CB8E71849D82C18                246
26   655000  E228EF481D53FF74                  1
27   655500  EDD0ACE12F2B124B                400
28   657000  650108FDBDA5A1E5                300
29   657500  4CE06740A3ED864D                100
..      ...               ...                ...
168  668000  60CE85217E125E92                 15
169  668000  6A9A8D29EA21CAA1                  8
170  668000  6BDDA4A97E785E38                 10
171  668000  6E852131D4DAB57A                 10
172  668000  C1C9ACF9E4E7C827                 27
173  668000  C30C24F984D86438                 10
174  668000  C4746310294B0B8B                  5
175  668000  C741ACE9CDB6AEF6                 20
176  668000  C915A4F1F276D236                 10
177  668000  CAABC74842512731                 60
178  668000  CD1B24A9D097B497                  5
179  668000  CD8CA4F971F05510                  1
180  668000  CD9AACB9D5F5B4D5                  1
181  668000  E26F4F08D492B972                 15
182  668000  E70F00F9F1D5D175                  6
183  668000  E8460529B5A39623                 10
184  668000  EA1E0129D81EB89E                  1
185  668000  EA9A8D29823E62BE                 10
186  668000  EC206F401CE101E1                 60
187  668000  EE01A139E78FC82F                 10
188  668500  4ACA0121B75797D7                 10
189  668500  4B8CA4F97F185E78                  8
190  668500  60468D213C1B1C9B                 10
191  668500  6301A0E11C9EFBDF                 10
192  668500  67170CF165854945                 10
193  668500  67DD24A1AC668FA6                  4
194  668500  C3C520E18E976DD7                 10
195  668500  CA4A01215ED43F54                 27
196  668500  CF1DA8B17DE46124                 10
197  668500  E4552971414221E2                 10

[198 rows x 3 columns]

In [17]:
data.TimeStamp.unique()[2000]

'2014-01-22D09:16:30.273821100'

In [18]:
data[(data.TimeStamp == '2014-01-22D09:16:30.273821100')]

,Series,SequenceNumber,TimeStamp,OrderNumber,OrderBookPosition,Price,QuantityDifference,Trade,BidOrAsk,BestPrice,BestQuantity
3167,CNF14,3168,2014-01-22D09:16:30.273821100,6EDD013159F73A77,1,668500,-8,,B,668500,10